### ISSUE TITLE
sqlite3的数据未按照程序建表

### ISSUE THREAD

**Issue by proudlily** [Unknwon/go-web-foundation#12]
在优才学院学习无闻老师的``go web基础``
在第3课模板用法讲解，额。用``orm建立表``，在后台运行成功，没有报错。
然后terminal终端，输入``sqlite3``,打开sqlite3的数据库
查看表 ``.databases``
显示
```
seq  name             file                                                      
---  ---------------  ----------------------------------------------------------
0    main 
```
没有表，请问这是怎么回事呢？是不是除了视频说的，还需要什么操作呢？

**Comment by proudlily** [comment]
额。。。是打开sqlite3的方法不对，应该进入到``/data``的目录下，输入
``sqlite3 beeblog.db ``
然后可以看见数据了
```
seq  name             file                                                      
---  ---------------  ----------------------------------------------------------
0    main            ～/golang/3rdpkg/src/web_bee/data/beeblog.db     
```

**Comment by Unknwon** [comment]
。。。 0 0

**Comment by yuching0163** [comment]
<img width="786" alt="1" src="https://user-images.githubusercontent.com/40746947/42611679-e49bcc4c-85c9-11e8-89f4-28cea93ad617.PNG">
想請問無聞老師，這個是甚麼問題，感謝
