### ISSUE TITLE
第四讲中的退出登陆请求不对

### ISSUE THREAD

**Issue by shuyaoyimei** [Unknwon/go-web-foundation#14]
在第四讲的T.nav.tpl中，当使用`<li><a href="/login?exit=true">退出登录</a></li>`时，无法退出登陆，但是当使用`<li><a href="/login?exit=tru">退出登录</a></li>`时，可以退出登录，不知道是beego的问题还是golang1.6的问题

**Comment by Sing-T** [comment]
你login.go里面的处理代码是怎样的？

**Comment by Unknwon** [comment]
视频已经过时。。我不建议继续看这套了。。

**Comment by Sing-T** [comment]
有别的推荐么？ 我最近也在看这个

**Comment by shuyaoyimei** [comment]
不好意思，这么晚才回复。login.go的逻辑应该和作者的代码一样的，主要心存疑问，所以一问。
ps:不知道作者大大对于新手有没有什么好的推荐

**Comment by Unknwon** [comment]
这个。。目前没有好的推荐。。:sweat:

**Comment by shuyaoyimei** [comment]
或者说有没有其他的开源项目可学习一下，这个博客我肯定还要跟着做的


无闻 <notifications@github.com>于2016年4月21日周四 上午3:00写道：
