### ISSUE TITLE
Go Web第一套教程

### ISSUE THREAD

**Issue by sakurasan** [Unknwon/go-web-foundation#15]
赶上更新了，刚把Beego版的看完，过程中beego版本原因，自己调试了好多bug，看这个视屏入门go开发太适合了。新版的Macaron不知和beego相比有什么不一样

**Comment by Unknwon** [comment]
1. Macaron 是我开发并维护的，所以会最大程度保证教程的有效期
2. 因为用的非常多。。所以可以讲的更加细致
3. 但是，Macaron 不适合所有人；同样的，没有框架使用所有人，所以这点我并不担心

**Comment by appleboy** [comment]
@Unknwon 期待您的視頻 ... 感謝你

**Comment by wingedFish** [comment]
soga

**Comment by dafeng** [comment]
Waiting for your update
