### ISSUE TITLE
beego 框架+mysql数据库问题

### ISSUE THREAD

**Issue by minnao** [Unknwon/go-web-foundation#18]
我按照示例代码输入：最后编译总报这个错怎么解
[ORM]2017/05/07 21:07:28 register db Ping `default`, Error 1049: Unknown database 'beeblog'
must have one register DataBase alias named `default`

**Comment by Unknwon** [comment]
hi 目前已！提供 beego 相关的支持。

不过你的错误很明显啊 没建数据库。。。
