### ISSUE TITLE
grpc是另一门语言么？求教学视频

### ISSUE THREAD

**Issue by fengweiqiang** [unknwon/go-web-foundation#29]
restful接口比grpc慢，grpc是另一门语法，那怎么用到项目中呢？另外我看到go语言能调用C语言代码，我把C语言项目从github拉下来却不知道怎么调用，每个文件都是一样的后缀，这个视频能否给大家普及一下^_^

**Comment by Unknwon** [comment]
不是额，只是个通信协议，不过确实可以加到教程里（虽然现在忙的连前面的铺垫都没空录...）

**Comment by fengweiqiang** [comment]
期待无闻大大讲grpc加入到教程中，实例确实能成功访问，但是不知道项目中怎么使用

**Comment by quede** [comment]
讲的不错可惜断更了

**Comment by 1987231487** [comment]
视频好像挂了，能更新下吗
