### ISSUE TITLE
在做web项目博客系统时遇到问题

### ISSUE THREAD

**Issue by vincentpeng335143003** [Unknwon/go-web-foundation#30]
有没有遇到这样的问题 ,mac环境下 谷歌搜了一下,没看懂
/Users/admin/Documents/go/pkg/tool/darwin_amd64/link: combining dwarf failed: Unknown load command 0x32 (50)
<img width="1228" alt="pasted graphic" src="https://user-images.githubusercontent.com/39480371/47903454-b1075380-debe-11e8-9a51-992ca1f471e2.png">

**Comment by Unknwon** [comment]
看起来像是编译器没配置好。。不属于本仓库可协助的知识范围。。建议谷歌。
