### ISSUE TITLE
无闻老师什么时候更新视频呢?期待期待期待期待

### ISSUE THREAD

**Issue by jinjiang2009** [Unknwon/go-web-foundation#34]
无闻老师什么时候更新视频呢?期待期待期待期待, 套用《复仇者联盟4》中一句话：期待3000. 从您的课程中学到不少，都是干货内容，老师简洁，幽默，随性的风格非常喜欢，现实中应该非常nice吧。可以考虑慕课网上出套视频，可以来些外快哦！！！期待支持！！！！

**Comment by 188660660** [comment]
无闻老师如果有时间出付费视频 会在第一时间订阅。。 学到了不少东西 也趟了不少坑 原来视频是 N年前录制 很牛  有一些地方框架和视频有出入啦 为无闻老师的开源精神点赞~

**Comment by Unknwon** [comment]
谢谢支持，不过现在工作了应该没有什么时间更新啦
