### ISSUE TITLE
lecture4 管理员登录后退出问题

### ISSUE THREAD

**Issue by chengsongyan** [unknwon/go-web-foundation#38]
你好：
正在学习您的视频，收获非常非常大，目前发现一个问题，在lecture4中，当管理员登录后 ，使用火狐浏览器不能退出，点击退出按钮没反应，火狐版本73.0.1（64位），使用搜狗浏览器可以正常退出，想知道是什么原因。

谢谢！

**Comment by chengsongyan** [comment]
补充下，是旧版本的lecture4

**Comment by unknwon** [comment]
。。。老铁，视频太老啦，我不能说确切原因，但是一般是 cookie 没清掉导致的。
